//
// Created by ruben on 24/11/2021.
//

#ifndef AIRPORTMANAGEMENT_AED_PROJECT_PASSENGER_H
#define AIRPORTMANAGEMENT_AED_PROJECT_PASSENGER_H


class Passenger {

};


#endif //AIRPORTMANAGEMENT_AED_PROJECT_PASSENGER_H
